import {photo} from '../components/photos.mjs';
import {redesignedHome,redesignedServices,redesignedContact,additionalAgencyPages,directWorkCard} from './agency-redesign.mjs';
import { site, faqs } from '../data/site.mjs';
import { examples } from '../data/examples.mjs';
import { icon, mark, button, textLink, eyebrow, priceCard, faqList, preview, devicePreview, workCard, pageHero, cta, escape } from '../components/ui.mjs';

function pricing() { return `${pageHero('Pricing','A proper website.<br>A clear monthly price.','Five connected services for local businesses: your website, inquiry follow-up, missed-call replies, review requests, and on-page SEO.')}<section class="section container" style="padding-top:0"><div class="price-grid pricing-offer"><div>${eyebrow('Made for local business')}<h2>Put your business<br>in a better light.</h2><p class="lead">Give your business a professional 10–20 page website, with practical systems to reply to inquiries, follow up with customers, and ask for reviews.</p><p class="lead">The package brings all five services together for $249/month. We’ll plan the pages and message flows with you, then confirm the full arrangement before you move forward.</p></div>${priceCard()}</div></section><section class="section surface"><div class="container"><div class="section-head"><div>${eyebrow('Clear before you commit')}<h2>The details belong<br>in the conversation.</h2></div><p>We’ll walk through these together so you know exactly what you’re agreeing to.</p></div><div class="principles-grid"><article><h3>Your website</h3><p>Your 10–20 pages, content, functionality, review process, and a realistic project timeline.</p></article><article><h3>Your monthly arrangement</h3><p>The full billing terms, any setup costs, commitment, ownership, and cancellation arrangements.</p></article><article><h3>After launch</h3><p>Messaging setup, usage allowances, any extra costs, hosting, maintenance, support, and future changes.</p></article></div></div></section><section class="section container"><div class="faq-layout"><div>${eyebrow('Before you decide')}<h2>A little more clarity.</h2></div>${faqList([faqs[1],faqs[12],faqs[9],faqs[10]])}</div></section>${cta()}`; }

function exampleIndex() { return `${pageHero('Five businesses. Five different approaches.','Find a website<br>that feels like your business.','Every example has 10 pages to explore: service details, photographs, useful answers, and a clear inquiry path. Open one and see the whole experience.')}<nav class="container industry-filter" aria-label="Jump to an industry">${examples.map(e=>`<a href="#${e.slug}">${e.category}${icon('arrow')}</a>`).join('')}</nav><section class="section container examples-expanded"><p class="collection-disclosure">Original website examples for fictional businesses. These are design concepts, not client projects.</p><div class="work-grid">${examples.map(directWorkCard).join('')}</div></section>${cta('Something you like?<br>Let’s make it your own.')}`; }

export function exampleDetail(e) { return `${pageHero(`${e.category} / Example concept`,escape(e.name),e.description)}<div class="container"><div class="case-hero" style="margin-bottom:2rem"><p class="small">Original website concept · Fictional business · ${e.pages.length} pages</p>${button('Explore the full website',`/demos/${e.slug}/`)}</div><div class="case-art ${e.theme}">${devicePreview(e)}</div></div><section class="section container"><div class="case-details"><div>${eyebrow('The design brief')}<h2>${e.style}</h2><p>${e.brief}</p><h3>The intended experience</h3><p>${e.outcome}</p></div><div>${eyebrow('A closer look')}<h2>Designed around<br>the business.</h2><p>${e.approach}</p><h3>Explore the details</h3><ul>${e.features.map(f=>`<li>${f}</li>`).join('')}</ul><h3>Explore the pages</h3><ul class="page-links">${e.pages.map((p,i)=>`<li><a href="/demos/${e.slug}/${e.routes[i] ? `${e.routes[i]}/` : ''}">${p}${icon('diagonal')}</a></li>`).join('')}</ul></div></div><aside class="note-box" style="margin-top:3rem"><p>This is an example for a fictional business, not a client project. Business names, offerings, and content are fictional. Photographs are illustrative. Example forms do not make real bookings or send inquiries.</p></aside></section><section class="section surface"><div class="container"><div class="section-head"><div>${eyebrow('Keep exploring')}<h2>Another business.<br>Another approach.</h2></div>${textLink('All examples','/examples/')}</div><div class="work-grid work-grid--pair">${examples.filter(x=>x.slug!==e.slug).map(workCard).join('')}</div></div></section>${cta('Something like this.<br>Made for your business.')}`; }

function about() { return `${pageHero('About SkipManual','For the people with<br>a business to run.','Your days are already full. Building a professional online presence shouldn’t mean becoming a designer, writer, or website expert on top of everything else.')}<section class="section container" style="padding-top:0"><div class="about-split"><div class="about-photo">${photo('cafe',{eager:true})}</div><div>${eyebrow('Why SkipManual exists')}<h2>Good work deserves<br>a good website.</h2><p>Local businesses put care into the details: the way a job is finished, how a customer is welcomed, the experience someone comes back for.</p><p>We believe a website should reflect that same care. SkipManual brings your business into focus online, with clear information, thoughtful design, and an obvious next step.</p><p>We build the website and plan the customer follow-up with you: inquiry replies, missed-call texts, and review requests that fit the way you work. The aim is a clearer next step for your customers and a little less on your plate.</p></div></div></section><section class="container about-statement">${eyebrow('Our point of view')}<h2>A website shouldn’t need<br>an explanation.<br><span class="serif"><em>It should give one.</em></span></h2><p>What you do. Who it’s for. Why it matters. How to get in touch. When those things are clear, your website is doing its job.</p></section><section class="section container"><div class="section-head"><div>${eyebrow('How we work')}<h2>Thoughtful by design.<br>Straightforward by choice.</h2></div></div><div class="principles-grid"><article><h3>Clarity over complexity.</h3><p>Useful pages, understandable language, and decisions that help your customers find what they need.</p></article><article><h3>Character over sameness.</h3><p>A restaurant and an electrician have different customers and different needs. Their websites should reflect that.</p></article><article><h3>Honesty from the start.</h3><p>Our examples are clearly identified as fictional businesses. Our scope is agreed with you. We let the work speak without invented reviews or results.</p></article></div></section>${cta()}`; }

function faq() { const cats = [...new Set(faqs.map(f=>f.category))]; return `${pageHero('Common questions','A few things,<br>made clear.','New to websites, comparing options, or just working out what you need? Start here.')}<section class="container section faq-page" style="padding-top:0"><nav class="faq-index" aria-label="FAQ topics">${cats.map((c,i)=>`<a href="#topic-${i}">${c}</a>`).join('')}</nav><div>${cats.map((c,i)=>`<section class="faq-group" id="topic-${i}"><h2>${c}</h2>${faqList(faqs.filter(f=>f.category===c))}</section>`).join('')}</div></section>${cta('Still have something<br>on your mind?')}`; }

function privacy() { return `${pageHero('Website information','Your information,<br>handled clearly.','A plain-language note about this website and its inquiry form.')}<section class="container section" style="padding-top:0"><div class="prose"><h2>The current website</h2><p>This website does not include analytics, advertising trackers, or marketing cookies. Fonts and images are served with the website rather than requested from third-party asset services.</p><h2>The inquiry form</h2><p>${site.contactEndpoint ? 'When you submit an inquiry, the information you enter is sent to our configured inquiry service to support a response to your request.' : site.email ? 'The inquiry form prepares a message in your email application. You choose whether to send it. Your email provider handles the sending of that message.' : 'The inquiry form currently prepares a brief in your browser. It does not send information to SkipManual. You can copy the brief or download it as a text file.'}</p><p>The form does not save your entries in browser storage. If you leave the page, you may lose what you typed. A brief you download stays on your device until you remove it.</p><h2>Example websites</h2><p>The example websites are fictional. Their forms demonstrate an interaction locally in your browser and do not send messages, make reservations, or create class bookings. Please use sample information when exploring them.</p><h2>Booking a call</h2><p>${site.bookingUrl ? 'The booking button opens our external scheduling provider. That provider handles appointment details and confirmation under its own privacy terms.' : 'The call page currently lets you prepare a local request. It does not reserve a time or send your information.'}</p><h2>Website hosting</h2><p>A hosting provider may process routine request information to serve and secure the site. The provider and any additional privacy details need to be confirmed when the website is published.</p><h2>Before a service agreement</h2><p>Project terms and any additional information about handling customer data will be provided as part of the service agreement. This page describes the website’s current behavior; it is not a substitute for those terms.</p>${textLink('Back to get started','/contact/')}</div></section>`; }

function information() { return `${pageHero('Website information','A clear note<br>about what you’re seeing.')}<section class="container section" style="padding-top:0"><div class="prose"><h2>About SkipManual</h2><p>SkipManual designs and builds professional websites for local businesses. The current base website package is $249 per month, in US dollars. Scope and full contractual terms are confirmed before an agreement.</p><h2>Original example concepts</h2><p>Current Electric, Ridgeline Roofing, Clearflow Plumbing, Form Studio, and Olive &amp; Ember are fictional businesses created for these examples. Their names, copy, services, menu items, class schedules, and forms are illustrative. They are not client projects and do not represent real business results.</p><h2>Photography</h2><p>The example websites use illustrative photography sourced from Unsplash. The photographs are not representations of actual SkipManual clients, facilities, team members, or completed projects.</p><h2>Service terms</h2><p>This website is an introduction to the service, not the service agreement. Exact inclusions, billing, ownership, cancellation, and ongoing responsibilities are discussed and agreed before work begins.</p>${textLink('Explore the service','/services/')}</div></section>`; }

export const agencyPages = [
  ...additionalAgencyPages,
  { path:'/', title:'Websites & Customer Follow-Up for Local Businesses | SkipManual', description:'A 10–20 page website and customer follow-up for your local business, all in one $249/month package. Explore five complete example websites and get started.', render:redesignedHome },
  { path:'/services/', title:'What’s Included in the $249 Website Package | SkipManual', description:'A 10–20 page website, inquiry follow-up, missed-call text replies, review requests, and on-page SEO. Explore the five services in SkipManual’s $249/month package.', render:redesignedServices },
  { path:'/pricing/', title:'The $249/Month Website Package | SkipManual', description:'Explore SkipManual’s $249/month local business website package. We confirm your project scope, full costs, and terms before you commit.', render:pricing },
  { path:'/examples/', title:'Website Examples & Original Concepts | SkipManual', description:'Explore five original website examples for electricians, roofers, plumbers, wellness studios, and restaurants. Browse every page of these fictional business concepts.', render:exampleIndex },
  { path:'/about/', title:'About SkipManual | Good Websites. Less on Your Plate.', description:'SkipManual helps local businesses look professional online with thoughtful website design, clear communication, and a straightforward approach.', render:about },
  { path:'/faq/', title:'Your Website Questions, Answered | SkipManual', description:'Straight answers about SkipManual’s website service, pricing, process, example work, and getting started. Learn what is agreed before your project begins.', render:faq },
  { path:'/contact/', title:'Let’s Build Your Business Website | SkipManual', description:'Tell SkipManual about your local business and the website you have in mind. Start with a short brief and explore the $249/month website package.', render:redesignedContact },
  { path:'/privacy/', title:'Website Privacy Information | SkipManual', description:'Learn how the SkipManual website currently handles inquiry forms, example interactions, browser storage, and third-party services.', render:privacy },
  { path:'/website-information/', title:'Website & Example Information | SkipManual', description:'Information about SkipManual, its fictional example websites, illustrative photography, and the distinction between website information and service terms.', render:information },
  { path:'/404/', title:'Page Not Found | SkipManual', description:'This page could not be found. Explore SkipManual’s website services and example collection.', noindex:true, render:()=>`${pageHero('404 / A small wrong turn','Let’s get you<br>back on track.','That page isn’t here. The rest of the site is ready to explore.')}<div class="container section" style="padding-top:0"><div class="actions">${button('Back to the homepage','/')}${textLink('Explore the examples','/examples/')}</div></div>` },
];
