export { studioHome as conversionHome } from '../components/studio-home.mjs';
import { examples } from '../data/examples.mjs';
import { packageServices } from '../data/package.mjs';
import { systemStory } from '../components/customer-film.mjs';
import { icon, button, textLink, eyebrow, escape, preview } from '../components/ui.mjs';

const symbols={current:'bolt',ridgeline:'roof',clearflow:'water',form:'flower',olive:'food'};
const tradeNames={current:'Electricians',ridgeline:'Roofers',clearflow:'Plumbers',form:'Studios',olive:'Restaurants'};

export function portfolioCard(e){return `<article class="portfolio-card portfolio-card--${e.theme}" id="${e.slug}"><a class="portfolio-image" href="/demos/${e.slug}/" aria-label="Explore all 10 pages of ${escape(e.name)}">${preview(e)}<span class="portfolio-open">Explore the website ${icon('diagonal')}</span></a><div class="portfolio-meta"><div><p>${e.category} <span>· 10-page prototype</span></p><h3><a href="/demos/${e.slug}/">${escape(e.name)}</a></h3></div><a href="/examples/${e.slug}/" class="portfolio-details" aria-label="About the ${escape(e.name)} design">${icon('arrow')}</a></div></article>`;}

function pricing(){return `<section class="section friendly-pricing"><div class="container"><div class="friendly-price-copy">${eyebrow('A little less on your plate')}<h2>One website.<br>All the follow-up.<br><em>One simple package.</em></h2><p>A proper home for your business online, with helpful replies for the moments you’re busy.</p></div><div class="friendly-price-card"><p class="price-card-label">THE LOCAL BUSINESS PACKAGE</p><div class="friendly-price"><strong>$249</strong><span>/ month<br><small>USD</small></span></div><p>Built around your business. All five included.</p><ul>${packageServices.map(s=>`<li>${icon('check')}${s.short}</li>`).join('')}</ul>${button('Let’s talk about your business','/book/')}<p class="friendly-price-note">We’ll confirm the scope, any extra costs, and full terms before you commit.</p>${textLink('See the pricing details','/pricing/')}</div></div></section>`;}

export function conversionServices(){return `<section class="page-hero container friendly-services-hero">${eyebrow('All five included. $249/month.')}<h1>A great website.<br><em>And the follow-through.</em></h1><p class="lead">Help people find your services, get in touch, and hear back. See how each part works below.</p>${button('Talk about your business','/book/')}</section>${systemStory({standalone:true})}<section class="section container included-simple"><div>${eyebrow('The practical details')}<h2>Here’s what<br><em>you’re getting.</em></h2><p>We plan the pages and messages around your business, then agree on the scope together.</p></div><div>${packageServices.map((s,i)=>`<details id="${s.id}" class="included-detail"><summary><span>0${i+1}</span>${s.short}${icon('arrow')}</summary><p>${s.description}</p><ul>${s.points.map(p=>`<li>${p}</li>`).join('')}</ul></details>`).join('')}</div></section>${pricing()}<section class="friendly-final"><div class="container"><div><h2>A little less on your plate.<br><em>A clearer next step.</em></h2><p>Let’s talk about what would help your business.</p></div>${button('Get started','/book/')}</div></section>`;}

export function conversionExamples(){return `<section class="page-hero container portfolio-page-hero">${eyebrow('Five businesses. Five personalities.')}<h1>Find your kind<br><em>of website.</em></h1><p class="lead">Go beyond the homepage. Explore ten working pages, useful service guides, and simple forms in every prototype.</p></section><nav class="container portfolio-filters" aria-label="Jump to a business type">${examples.map(e=>`<a href="#${e.slug}">${icon(symbols[e.theme])}${tradeNames[e.theme]}</a>`).join('')}</nav><section class="section container portfolio-collection"><div class="portfolio-grid">${examples.map(portfolioCard).join('')}</div><p class="portfolio-disclosure">Fictional businesses. Fully built prototypes. These demonstrate our design approach and are not client projects.</p></section><section class="friendly-final"><div class="container"><div><h2>See something you like?<br><em>Let’s make it yours.</em></h2><p>A starting point for your own business, your own services, your own style.</p></div>${button('Talk about your website','/book/')}</div></section>`;}
