import {extraRoutes,allPagesNavigation,exampleHomeExtension,expandedNavigation,requestParameters} from './example-expansion.mjs';
import { isReferenceTrade, referenceHome, referenceShell } from './reference-trades.mjs';
import {photo} from '../components/photos.mjs';
import { tradeRoutes } from './trades.mjs';
import { examples } from '../data/examples.mjs';
import { icon, escape, faqList } from '../components/ui.mjs';

const config = {
  clearflow: { links:[['Plumbing services','services'],['Water heaters','water-heaters']], action:'Request a visit', contact:'request-a-visit', footer:'A little help. A home that works.' },
  ridgeline: { links:[['Roofing services','roofing'],['Repair or replace?','repair-or-replace']], action:'Request an assessment', contact:'request-an-assessment', footer:'Good homes. Sound roofs. A considered next step.' },
  olive: { links:[['Menu','menu'],['Our story','our-story']], action:'A table for you', contact:'book-a-table', signature:'Seasonal food. Shared moments.', footer:'Good food. Unhurried evenings. A place at the table.' },
  current: { links:[['Our services','services'],['Lighting & upgrades','lighting']], action:'Request a quote', contact:'request-a-quote', signature:'Thoughtful work. A brighter home.', footer:'Considered electrical work for the place you call home.' },
  form: { links:[['Classes','classes'],['The studio','the-studio']], action:'Find your class', contact:'find-your-class', signature:'Space to move. Room to be yourself.', footer:'Mindful movement. A stronger connection to yourself.' },
};
const dlink = (e, label, route='', cls='demo-button', parameters={}) => {
  const query=new URLSearchParams(parameters).toString();
  if(route.startsWith('#'))return `<a class="${cls}" href="${escape(route)}">${label}${icon('diagonal')}</a>`;
  return `<a class="${cls}" href="/demos/${e.slug}/${route ? `${route}/` : ''}${query ? `?${escape(query)}` : ''}">${label}${icon('diagonal')}</a>`;
};
const dimage = (src,alt,cls='',eager=false) => photo(src,{alt,cls,eager});
const dkicker = s => `<p class="demo-kicker">${s}</p>`;

function shell(e, page, content) {
  const c = config[e.theme];
  const requestTarget=page===c.contact?'#demo-request':c.contact;
  const parameters=requestParameters(e,page);
  const nav = c.links.map(([label,path])=>`<a href="/demos/${e.slug}/${path}/" ${page===path ? 'aria-current="page"' : ''}>${label}</a>`).join('');
  return `<a class="skip-link" href="#demo-main">Skip to website content</a><aside class="demo-banner" aria-label="Example website notice"><div><span class="demo-pill">EXAMPLE WEBSITE</span><span>Fictional business. Real design possibilities.</span></div><div><a href="/examples/${e.slug}/">Back to concept</a><a href="/book/?example=${e.slug}">Want one like this? ${icon('arrow')}</a></div></aside><div class="demo-shell theme-${e.theme}"><header class="demo-header demo-container"><a class="demo-brand" href="/demos/${e.slug}/">${e.theme==='current' ? icon('bolt') : e.theme==='clearflow' ? icon('water') : e.theme==='ridgeline' ? icon('roof') : ''}${escape(e.name)}${e.theme==='form' ? '<sup></sup>' : ''}</a><nav class="demo-nav" aria-label="Example website navigation">${nav}${allPagesNavigation(e,page)}${dlink(e,c.action,requestTarget,'demo-button',parameters)}</nav><details class="demo-mobile"><summary>Menu</summary><nav aria-label="Example mobile navigation">${e.routes.map((route,i)=>`<a href="/demos/${e.slug}/${route?route+'/':''}" ${page===route?'aria-current="page"':''}>${e.pages[i]}</a>`).join('')}</nav></details></header><div id="demo-main">${expandedNavigation(e)}${content}</div><footer class="demo-footer"><div class="demo-container"><div class="demo-footer-top"><div><a class="demo-brand" href="/demos/${e.slug}/">${escape(e.name)}</a><p>${c.footer}</p></div><nav aria-label="Example footer navigation">${e.routes.map((route,i)=>`<a href="/demos/${e.slug}/${route?route+'/':''}">${e.pages[i]}</a>`).join('')}</nav></div><div class="demo-footer-bottom"><span>A fictional ${e.category.toLowerCase()} concept by SkipManual. <a href="/website-information/#photo-credits">Photo credits</a></span><a href="/examples/${e.slug}/">About this example ${icon('arrow')}</a></div></div></footer><nav class="example-mobile-action" aria-label="Quick website actions"><a href="/demos/${e.slug}/questions/">Questions?</a>${dlink(e,c.action,requestTarget,'demo-button',parameters)}</nav></div>`;
}

function oliveHome(e) { return `<section class="olive-hero">${dimage('restaurant','Seasonal food, carefully plated for a restaurant meal','',true)}<div class="olive-hero-copy">${dkicker('A neighborhood table. A seasonal kitchen.')}<h1>Good food.<br><em>Great company.</em></h1><p>For a slow supper, a long catch-up,<br>and the simple pleasure of eating well.</p>${dlink(e,'Come hungry. Stay a while.','menu')}</div><span class="olive-hero-foot">OLIVE &amp; EMBER &nbsp; / &nbsp; THE SEASONAL TABLE</span></section><div class="demo-ribbon"><span>Seasonal by nature.</span><span>Generous by choice.</span><span>Best enjoyed together.</span></div><section class="demo-section demo-container olive-intro"><div>${dkicker('From the kitchen')}<h2>A little fire.<br>A lot of <em>feeling.</em></h2></div><div><p>Bright produce. Deep, slow-cooked flavors. A menu that lets good ingredients do what they do best.</p><p>Start with something to share. Find a new favorite. Leave a little room for dessert. There’s no need to rush.</p>${dlink(e,'Explore the menu','menu','demo-text-link')}</div></section><section class="olive-feature demo-container"><div>${dimage('interior','Warm restaurant dining room with wooden tables and pendant lighting')}</div><div>${dkicker('Make an evening of it')}<h2>The kind of place<br>you settle <em>into.</em></h2><p>Pull up a chair. Order another small plate. Let the conversation wander. The best thing on the table might just be the company.</p>${dlink(e,'A little about us','our-story','demo-text-link')}</div></section><section class="demo-section demo-container"><div class="demo-section-head">${dkicker('A taste of the season')}<h2>Worth gathering <em>around.</em></h2></div><div class="dish-grid"><article><span>TO BEGIN</span><h3>Whipped ricotta</h3><p>Roasted grapes, thyme honey, grilled sourdough.</p></article><article><span>FROM THE FIRE</span><h3>Charred market vegetables</h3><p>White bean purée, green herb dressing, toasted seeds.</p></article><article><span>SOMETHING SWEET</span><h3>Olive oil cake</h3><p>Citrus curd, crème fraîche, candied peel.</p></article></div>${dlink(e,'See the full menu','menu','demo-text-link')}</section><section class="demo-closing"><div class="demo-container">${dkicker('There’s a place for you here')}<h2>Let’s make<br>an <em>evening of it.</em></h2>${dlink(e,'Find a table','book-a-table')}</div></section>`; }

const menus = [
  ['To begin', [['Whipped ricotta','Roasted grapes, thyme honey, grilled sourdough','12'],['Little gem salad','Buttermilk dressing, shaved radish, sourdough crumb','11'],['Warm marinated olives','Orange peel, rosemary, a little chili','7']]],
  ['From the kitchen', [['Charred market vegetables','White bean purée, green herbs, toasted seeds','22'],['Roasted chicken','Creamy polenta, wilted greens, pan jus','27'],['Mushroom pappardelle','Roasted mushrooms, pecorino, fresh parsley','24'],['Seared seasonal fish','Braised fennel, lemon, caper butter','29']]],
  ['Something sweet', [['Olive oil cake','Citrus curd, crème fraîche, candied peel','10'],['Dark chocolate crémeux','Sea salt, hazelnut, cultured cream','11'],['Seasonal sorbet','Two scoops of something bright','7']]],
];
function oliveMenu(e) { return `<section class="demo-page-hero demo-container">${dkicker('The seasonal menu')}<h1>Good things,<br><em>in their own time.</em></h1><p>A little to share. Something to savor.<br>See what’s coming from the kitchen.</p></section><section class="demo-container menu-layout"><nav class="menu-index" aria-label="Menu sections">${menus.map(([n],i)=>`<a href="#menu-${i}">${n}</a>`).join('')}</nav><div>${menus.map(([name,items],i)=>`<section class="menu-category" id="menu-${i}">${photo(['seasonal-plate','restaurant','dessert'][i],{cls:'menu-category-photo'})}<h2>${name}</h2>${items.map(([n,d,p])=>`<article class="menu-dish"><div><h3>${n}</h3><p>${d}</p></div><span>$${p}</span></article>`).join('')}</section>`).join('')}<p class="demo-fine">Illustrative menu and prices for this fictional example. Dietary and allergen information would be confirmed by the real restaurant.</p></div></section><section class="demo-closing"><div class="demo-container"><h2>Better with <em>company.</em></h2>${dlink(e,'Find a table','book-a-table')}</div></section>`; }

function oliveStory(e) { return `<section class="demo-page-hero demo-container">${dkicker('The thought behind the table')}<h1>Food brings us in.<br><em>People make us stay.</em></h1></section><div class="demo-container demo-wide-image">${dimage('interior','Inviting restaurant dining room with warm lighting','',true)}</div><section class="demo-section demo-container olive-intro"><h2>A neighborhood<br><em>state of mind.</em></h2><div><p>Olive &amp; Ember is a concept built around one simple pleasure: sitting down to a good meal with people you want to spend time with.</p><p>The kitchen follows the season. The room makes space for a quick bite or an unhurried evening. The food is generous, familiar in the best way, and full of little details worth noticing.</p><p>No occasion required. Just an appetite.</p></div></section><section class="demo-container dish-grid story-values"><article><h3>Follow the season.</h3><p>Let what’s fresh guide what goes on the plate.</p></article><article><h3>Keep it generous.</h3><p>Food made for passing around and trying a little of everything.</p></article><article><h3>Make room.</h3><p>For familiar faces, new conversations, and one more course.</p></article></section><section class="demo-closing"><div class="demo-container"><h2>Pull up <em>a chair.</em></h2>${dlink(e,'Explore the menu','menu')}</div></section>`; }

const services = [
 ['01','Lighting & upgrades','From a more useful kitchen to a warmer evening glow. Thoughtful lighting for how you actually live.','lighting'],
 ['02','Repairs & fault finding','For the switch that stopped working, the outlet that needs attention, or the problem you can’t quite explain.','repairs'],
 ['03','Installations & additions','New fixtures, additional outlets, and practical improvements that make your home work better for you.','installations'],
 ['04','Renovation electrical','Plan the electrical side of a refreshed room around the way the space will be used.','renovations'],
];
function currentHome(e) { return `<section class="demo-container current-hero"><div>${dkicker('Residential electrical. Clearly considered.')}<h1>Good energy.<br>Expertly wired<span>.</span></h1><p>From the lights you live by to the outlets you rely on. Practical electrical work, explained in plain language.</p>${dlink(e,'Let’s talk about your project','request-a-quote')}<p class="current-hero-note">Your home. Your questions. A clear next step.</p></div><div class="current-hero-image">${dimage('electrician','Electrical professional working on a wiring installation','',true)}<span>${icon('bolt')}Make your home work better.</span></div></section><div class="current-strip"><div class="demo-container"><span>${icon('home')}Work around your home</span><span>${icon('layout')}Options explained clearly</span><span>${icon('cursor')}A straightforward next step</span></div></div><section class="demo-section demo-container"><div class="demo-section-head split"><div>${dkicker('How we can help')}<h2>The small fixes.<br>The bigger plans.</h2></div><p>Whatever brought you here, start with the job.<br>We’ll help make the next step clear.</p></div><div class="electrical-services">${services.slice(0,3).map(([n,h,p,r])=>`<article><span>${n} /</span><h3>${h}</h3><p>${p}</p>${dlink(e,'Explore this service',r,'demo-text-link')}</article>`).join('')}</div></section><section class="current-process"><div class="demo-container demo-section"><div>${dkicker('Let’s keep it simple')}<h2>Less guesswork.<br>More getting it sorted.</h2></div><ol><li><span>01</span><div><h3>Tell us what’s going on.</h3><p>A small repair, a new idea, or a full renovation. Start with what you know.</p></div></li><li><span>02</span><div><h3>Understand your options.</h3><p>The scope, practical choices, and next steps should be clear before any work.</p></div></li><li><span>03</span><div><h3>Make a plan for the work.</h3><p>Agree on what needs doing and how it fits around your home.</p></div></li></ol></div></section><section class="demo-section demo-container current-faq"><h2>A little clarity<br>goes a long way.</h2>${faqList([{q:'What should I include in my request?',a:'Describe the issue or project, the room involved, and what you would like to change. You do not need to know the technical name.'},{q:'Can I ask about more than one job?',a:'Yes. Include the different tasks in one request so they can be considered together.'},{q:'Does this example accept real electrical jobs?',a:'No. Current Electric is a fictional website concept. The request form demonstrates an inquiry flow only.'}])}</section><section class="demo-closing"><div class="demo-container"><h2>Let’s shed some light<br>on your next project.</h2>${dlink(e,'Start a project request','request-a-quote')}</div></section>`; }
function currentServices(e) { return `<section class="demo-page-hero demo-container">${dkicker('Residential electrical services')}<h1>A more comfortable home.<br>A brighter <span>everyday.</span></h1><p>Practical improvements and thoughtful repairs.<br>Find the work that fits what you need.</p></section><section class="demo-container electrical-service-list">${services.map(([n,h,p,r])=>`<article><span>${n}</span><h2>${h}</h2><div><p>${p}</p>${dlink(e,'Explore this service',r,'demo-text-link')}</div></article>`).join('')}</section><section class="demo-closing"><div class="demo-container"><h2>Not sure what to call it?<br>Just tell us what it does.</h2>${dlink(e,'Describe your project','request-a-quote')}</div></section>`; }
function currentLighting(e) { return `<section class="demo-page-hero demo-container">${dkicker('Services / Lighting & upgrades')}<h1>See your home<br>in a better <span>light.</span></h1><p>Useful where you work. Softer where you unwind.<br>Lighting that fits the way your home feels.</p></section><section class="demo-container current-lighting"><div>${dimage('lighting-install','An electrician replacing a ceiling light ballast','',true)}</div><div><h2>The right light<br>changes a room.</h2><p>A kitchen that needs brighter task lighting. A hallway that feels too dim. A living room that could use a more welcoming glow. Start with the way you use the space.</p><ul><li>Interior fixture replacements</li><li>Task and accent lighting</li><li>Dimmer and switch updates</li><li>Lighting plans for renovated rooms</li></ul>${dlink(e,'Talk about your lighting','request-a-quote','demo-button',{service:'Lighting & upgrades'})}</div></section><section class="demo-section demo-container"><div class="demo-section-head"><h2>A few helpful things to know.</h2></div><div class="electrical-services"><article><span>01 /</span><h3>The room</h3><p>Where do you need a change, and what do you use that space for?</p></article><article><span>02 /</span><h3>The feeling</h3><p>Brighter, warmer, easier to adjust? Describe what is missing.</p></article><article><span>03 /</span><h3>The fixture</h3><p>Share whether you have chosen a light or want to discuss options.</p></article></div></section>`; }

const classes = [
 {name:'Foundations',type:'Start here',level:'Beginner',text:'Get comfortable with the essentials. A steady, welcoming class with time to understand each movement.',duration:'50 minutes'},
 {name:'Everyday Flow',type:'Find your rhythm',level:'Open level',text:'A balanced full-body session that connects strength, control, and a little more ease.',duration:'50 minutes'},
 {name:'Strength & Length',type:'Build from within',level:'Experienced',text:'A more focused challenge, bringing thoughtful resistance and controlled movement together.',duration:'55 minutes'},
];
const schedule = [['Monday','07:00','Everyday Flow','Open level'],['Monday','18:00','Foundations','Beginner'],['Wednesday','09:00','Foundations','Beginner'],['Wednesday','18:30','Strength & Length','Experienced'],['Friday','07:30','Everyday Flow','Open level'],['Friday','12:00','Foundations','Beginner'],['Saturday','09:00','Everyday Flow','Open level'],['Saturday','10:30','Strength & Length','Experienced']];
function formHome(e) { return `<section class="demo-container form-hero"><div>${dkicker('Mindful movement. Everyday strength.')}<h1>A little movement.<br><em>A lot more you.</em></h1><p>A Pilates practice with room for where you are.<br>Find your strength, your rhythm, and a little space<br>just for yourself.</p>${dlink(e,'Find your first class','classes')}<span class="form-hero-caption">COME AS YOU ARE. MOVE FROM THERE.</span></div><div class="form-hero-image">${dimage('pilates-reformer','Pilates practice on a reformer in a light-filled studio','',true)}<span>make space<br><em>for yourself.</em></span></div></section><div class="form-ribbon"><span>Move with intention.</span><span>Build from within.</span><span>Feel more like you.</span></div><section class="demo-section demo-container form-intro">${dkicker('A different kind of energy')}<h2>Less keeping up.<br>More <em>tuning in.</em></h2><p>You don’t need to be flexible. You don’t need to know the moves. Start where you are, pay attention to how you feel, and build a practice that belongs to you.</p>${dlink(e,'Meet the studio','the-studio','demo-text-link')}</section><section class="demo-section demo-container" style="padding-top:0"><div class="demo-section-head split"><div>${dkicker('Find your way to move')}<h2>Your pace.<br><em>Your practice.</em></h2></div>${dlink(e,'Explore all classes','classes','demo-text-link')}</div><div class="class-grid">${classes.map((c,i)=>`<article><span class="class-symbol symbol-${i}" aria-hidden="true">${['◒','◌','✳'][i]}</span>${dkicker(c.type)}<h3>${c.name}</h3><p>${c.text}</p><div class="class-meta"><span>${c.duration}</span><span>${c.level}</span></div>${dlink(e,'Try this class','find-your-class','demo-text-link',{class:c.name})}</article>`).join('')}</div></section><section class="demo-closing"><div class="demo-container">${dkicker('A little time, just for you')}<h2>Your first class.<br><em>A fresh place to start.</em></h2>${dlink(e,'Let’s find your class','find-your-class')}</div></section>`; }
function formClasses(e) { return `<section class="demo-page-hero demo-container">${dkicker('The classes')}<h1>Find your rhythm.<br><em>Make it your own.</em></h1><p>Different starting points. The same intention.<br>Movement that meets you where you are.</p></section><section class="demo-container class-grid">${classes.map((c,i)=>`<article><span class="class-symbol symbol-${i}" aria-hidden="true">${['◒','◌','✳'][i]}</span>${dkicker(c.level)}<h2>${c.name}</h2><p>${c.text}</p><div class="class-meta"><span>${c.duration}</span><span>${c.level}</span></div>${dlink(e,'Try this class','find-your-class','demo-text-link',{class:c.name})}</article>`).join('')}</section><section class="demo-section demo-container"><div class="demo-section-head"><div>${dkicker('A week at Form')}<h2>A little space<br>in <em>your schedule.</em></h2></div></div><p class="demo-fine" style="margin-bottom:1.5rem">Illustrative class schedule. This fictional studio does not accept real bookings.</p><div class="schedule-filters" role="group" aria-label="Filter schedule by day">${['All days','Monday','Wednesday','Friday','Saturday'].map((d,i)=>`<button type="button" data-day="${i===0?'all':d}" aria-pressed="${i===0}">${d}</button>`).join('')}</div><div class="schedule-list">${schedule.map(([d,t,c,l])=>`<article data-class-day="${d}"><span>${d}<strong>${t}</strong></span><h3>${c}<small>${l}</small></h3>${dlink(e,'Find a place','find-your-class','demo-text-link',{class:c})}</article>`).join('')}</div><p class="sr-only" data-schedule-status role="status" aria-live="polite"></p></section>`; }
function formStudio(e) { return `<section class="demo-page-hero demo-container">${dkicker('The studio')}<h1>A softer landing.<br><em>A stronger you.</em></h1><p>Space to notice how you move.<br>Encouragement to see what’s possible.</p></section><section class="demo-container studio-story"><div>${dimage('pilates-equipment','Pilates reformers arranged inside a bright training studio','',true)}</div><div><h2>Come as you are.<br><em>Really.</em></h2><p>Form is a studio concept for people who want to feel more at home in their bodies. A place where progress doesn’t need to be loud, and a first class doesn’t need to feel intimidating.</p><p>The practice is thoughtful. The atmosphere is warm. The goal is to leave feeling a little more connected than when you arrived.</p>${dlink(e,'Find your starting point','classes')}</div></section><section class="demo-section demo-container current-faq"><h2>Your first visit,<br><em>with a little less unknown.</em></h2>${faqList([{q:'I have never tried Pilates. Where would I start?',a:'Foundations is the introductory class in this example. It is designed around a steady pace and time to become familiar with the movements.'},{q:'What would I bring to a class?',a:'Comfortable clothes you can move in and a water bottle are a useful start. A real studio would confirm any equipment or grip-sock requirements before your visit.'},{q:'Can I book a real class here?',a:'No. Form Studio is a fictional concept created by SkipManual. You can explore the class request form to see how the experience works.'}])}</section>`; }

function demoContact(e) {
  const theme = e.theme;
  const isOlive = theme==='olive', isForm = theme==='form';
  const title = isOlive ? 'An evening<br><em>worth making time for.</em>' : isForm ? 'A first step.<br><em>At your own pace.</em>' : 'Tell us what<br>needs a <span>little attention.</span>';
  const fields = isOlive ? `<div class="field full"><label for="demo-occasion">Occasion <span>(optional)</span></label><input id="demo-occasion" name="occasion" maxlength="160" placeholder="Dinner, a birthday, or a group gathering"></div><div class="field"><label for="demo-date">Preferred date *</label><input id="demo-date" name="date" type="date" required></div><div class="field"><label for="demo-guests">Your table *</label><select id="demo-guests" name="guests" required><option value="">Choose party size</option><option>1 guest</option><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5–6 guests</option><option>7–10 guests</option><option>11–20 guests</option><option>More than 20 guests</option></select></div><div class="field full"><label for="demo-time">Preferred time *</label><select id="demo-time" name="time" required><option value="">Choose a time</option><option>17:30</option><option>18:30</option><option>19:30</option><option>20:30</option></select></div>` : isForm ? `<div class="field full"><label for="demo-class">A class that feels right *</label><select id="demo-class" name="class" required><option value="">Choose a class</option><option>Foundations</option><option>Everyday Flow</option><option>Strength &amp; Length</option><option>Private session</option><option>Help me choose</option></select></div><div class="field full"><label for="demo-experience">Your Pilates experience *</label><select id="demo-experience" name="experience" required><option value="">Choose what fits</option><option>This would be my first class</option><option>I have tried a few classes</option><option>I have a regular practice</option></select></div>` : `<div class="field full"><label for="demo-service">What can we help with? *</label><select id="demo-service" name="service" required><option value="">Choose a service</option><option>Lighting &amp; upgrades</option><option>Repairs &amp; fault finding</option><option>Installations &amp; additions</option><option>Renovation electrical</option><option>I’m not sure yet</option></select></div><div class="field full"><label for="demo-project">Describe your project *</label><textarea id="demo-project" name="project" required maxlength="2000" placeholder="For example: better lighting in the kitchen."></textarea></div>`;
  return `<section class="demo-page-hero demo-container">${dkicker(isOlive?'A table for you':isForm?'Find your class':'Let’s talk about your project')}<h1>${title}</h1></section><section class="demo-container demo-contact"><div><h2>${isOlive ? 'Bring an appetite.<br>We’ll set the scene.' : isForm ? 'Find a little<br>space for yourself.' : 'Start with what<br>you know.'}</h2><p>${isOlive ? 'Choose a date, a time, and the people you want to share a table with.' : isForm ? 'Let us know where you are starting. This request flow is designed to help you find the right class.' : 'You don’t need the technical words. Tell us what is happening, or what you would like to change.'}</p><aside class="demo-disclosure"><strong>This is an example website.</strong><p>${isOlive ? 'No table will be reserved.' : isForm ? 'No class will be booked.' : 'No electrical work will be requested.'} This is a fictional business. Please use sample details; the form does not send or store information.</p></aside></div><form id="demo-request" class="demo-request-form" tabindex="-1" data-demo-form data-demo-type="${theme}"><p class="form-intro">Explore the ${isOlive ? 'table request' : isForm ? 'class request' : 'project inquiry'} experience. * Required.</p><div class="form-grid"><div class="field full"><label for="demo-name">Sample name *</label><input id="demo-name" name="name" required maxlength="100" placeholder="Alex Example"></div>${fields}</div><button class="demo-button" type="submit" data-js-submit disabled>Preview ${isOlive ? 'table request' : isForm ? 'class request' : 'project request'}${icon('arrow')}</button><p class="form-feedback" role="status" aria-live="polite" tabindex="-1"></p><noscript><p>JavaScript is needed to preview this example interaction. No information is sent.</p></noscript></form></section>`;
}

export function demoPages() {
  return examples.flatMap(e=>{
    const c=config[e.theme];
    const routes=tradeRoutes[e.theme] ? [...tradeRoutes[e.theme]] : (e.theme==='olive' ? [['','Home',oliveHome],['menu','Menu',oliveMenu],['our-story','Our story',oliveStory]] : e.theme==='current' ? [['','Home',currentHome],['services','Services',currentServices],['lighting','Lighting & upgrades',currentLighting]] : [['','Home',formHome],['classes','Classes',formClasses],['the-studio','The studio',formStudio]]);
    if(!tradeRoutes[e.theme]) routes.push([c.contact,c.action,demoContact]);
    routes.push(...extraRoutes(e));
    return routes.map(([route,title,render])=>({path:`/demos/${e.slug}/${route ? `${route}/` : ''}`,title:`${title} | ${e.name} | SkipManual Example`,description:`Explore the ${title.toLowerCase()} page of ${e.name}, a fictional ${e.category.toLowerCase()} website concept designed by SkipManual. This is an illustrative example, not a real business.`,demo:true,bodyClass:'demo-body',render:()=>{
      let body=route===''&&isReferenceTrade(e)?referenceHome(e):render(e);
      if(route===''&&!isReferenceTrade(e)){
        const closing=Math.max(body.lastIndexOf('<section class="demo-closing"'),body.lastIndexOf('<section class="trade-closing"'));
        body=closing>=0?body.slice(0,closing)+exampleHomeExtension(e)+body.slice(closing):body+exampleHomeExtension(e);
      }
      return isReferenceTrade(e)?referenceShell(e,route,body):shell(e,route,body);
    }}));
  });
}
