import { photoLibrary } from '../data/example-content.mjs';
import { icon, escape } from '../components/ui.mjs';
import { photo } from '../components/photos.mjs';
import { allPagesNavigation, requestParameters } from './example-expansion.mjs';
import { serviceFinder } from './trades.mjs';

export const isReferenceTrade = e => ['current','clearflow','ridgeline'].includes(e.theme);
const target = e => e.theme==='current'?'request-a-quote':e.theme==='clearflow'?'request-a-visit':'request-an-assessment';
const href = (e, route='') => `/demos/${e.slug}/${route?route+'/':''}`;
const action = (e,label='Contact now',route=target(e),cls='demo-button') => `<a class="${cls}" href="${href(e,route)}">${label}${icon('arrow')}</a>`;
const kicker = text => `<p class="demo-kicker">${text}</p>`;
const tradeServices = {
  current:[['sun','Lighting & upgrades','A brighter room. A better everyday.','lighting'],['bolt','Electrical repairs','Find the fault. Make a clear plan.','repairs'],['home','New installations','The right connections for your home.','installations'],['tool','Renovations','Bring your next project to life.','renovations']],
  clearflow:[['water','Leaks & fixtures','For drips that won’t quit.','leaks-and-fixtures'],['flow','Blocked drains','Get things moving again.','drains'],['sun','Water heaters','Bring back the warm showers.','water-heaters'],['home','Kitchen & bath','Plumbing for your next refresh.','bathroom-kitchen']],
  ridgeline:[['roof','Roof repairs','A closer look at leaks and damage.','roof-repairs'],['home','Roof replacement','A fresh start, with a clear plan.','roof-replacement'],['layout','Roof materials','Find a finish that fits your home.','materials'],['check','Roof assessments','Understand your roof’s condition.','assessment-process']],
};

function serviceCards(e){return `<div class="ref-service-grid">${tradeServices[e.theme].map(([symbol,name,text,route])=>`<a href="${href(e,route)}"><span class="ref-service-symbol">${icon(symbol)}</span><h3>${name}</h3><p>${text}</p><span class="ref-service-more">Explore service ${icon('arrow')}</span></a>`).join('')}</div>`;}

function shortRequest(e){return `<form class="demo-request-form ref-quick-form" data-demo-form data-demo-type="${e.theme}"><p class="demo-kicker">Let’s start with your home</p><h2>${e.theme==='ridgeline'?'Request a roof assessment':'How can we help?'}</h2><p class="ref-form-note">Try this prototype with sample details.</p><div class="field"><label for="quick-name">Your name *</label><input id="quick-name" name="name" autocomplete="off" required maxlength="100" placeholder="Alex Example"></div><div class="field"><label for="quick-service">What do you need? *</label><select id="quick-service" name="service" required><option value="">Choose a service</option>${tradeServices[e.theme].map(([,name])=>`<option>${escape(name)}</option>`).join('')}<option>Help me choose</option></select></div><button class="demo-button" type="submit" data-js-submit disabled>Preview my request ${icon('arrow')}</button><p class="ref-form-note">Prototype only. Nothing is sent or booked.</p><p class="form-feedback" role="status" aria-live="polite" tabindex="-1"></p><noscript><p>Enable JavaScript to preview a request, or explore the service pages.</p></noscript></form>`;}

function closing(e){return `<section class="ref-closing"><div class="demo-container"><div>${kicker('One simple next step')}<h2>${e.theme==='current'?'Let’s brighten up your home.':e.theme==='clearflow'?'Let’s get your day flowing again.':'Your home. A sound roof. A clear plan.'}</h2><p>Tell us what needs attention. Start with what you know.</p></div>${action(e)}</div></section>`;}

function photoTiles(e){const images=e.theme==='current'?['lighting-install','electrical-panel','electrician']:e.theme==='clearflow'?['plumbing-sink-work','drain-inspection','water-heater-repair']:['roof-shingles','roof-crew','roof-tiles'];return `<section class="demo-section demo-container ref-photo-section"><div class="ref-section-head"><div>${kicker('A closer look at the work')}<h2>${e.theme==='ridgeline'?'Real roofing. Every layer.':'See what goes into the job.'}</h2></div>${action(e,'Explore the gallery','gallery','demo-text-link')}</div><div class="ref-photo-grid">${images.map(name=>`<a href="${href(e,'gallery')}" aria-label="Explore ${escape(e.name)} photography">${photo(name)}<span>${escape(photoLibrary[name][0])}</span></a>`).join('')}</div><p class="ref-image-note">Sourced photographs of real work, used to illustrate this fictional business. <a href="/website-information/#photo-credits">Photo credits</a></p></section>`;}

function electricHome(e){return `<section class="ref-electric-hero"><div class="ref-electric-photo">${photo('electrician',{eager:true})}</div><span class="ref-spark ref-spark-one" aria-hidden="true">✦</span><span class="ref-spark ref-spark-two" aria-hidden="true">✦</span><div class="demo-container"><div class="ref-electric-copy">${kicker('A little expertise. A brighter everyday.')}<h1>Good energy.<br><span>GREAT SERVICE.</span><br>That’s Current.</h1><p>Electrical repairs, lighting, and installations.<br>Let’s make your home work better.</p><div class="ref-hero-actions">${action(e)}${action(e,'Explore our services','services','ref-secondary')}</div><div class="ref-hero-points"><span>${icon('home')}Home electrical care</span><span>${icon('check')}Clear next steps</span></div></div></div><svg class="ref-wave" viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path fill="#b8e8f5" d="M0 62Q300-10 620 60T1440 35V100H0Z"/><path fill="#fff" d="M0 78Q320 6 640 74T1440 52V100H0Z"/></svg></section><section class="demo-container ref-electric-services">${serviceCards(e)}</section><section class="demo-section demo-container ref-electric-about"><div class="ref-about-photo">${photo('electrical-panel')}<span>${icon('bolt')}Small fixes.<br>Brighter days.</span></div><div class="ref-about-copy">${kicker('Good work starts with listening')}<h2>Your home deserves<br>a little <span>extra care.</span></h2><p>A flickering light. A new kitchen. The outlet that finally needs fixing. Whatever the job, start with a straightforward conversation.</p><ul class="ref-checks"><li>${icon('check')}The work explained in everyday language</li><li>${icon('check')}Options that fit the way you use your home</li><li>${icon('check')}A clear plan before the work begins</li></ul>${action(e,'Meet the approach','our-approach')}</div></section><section class="ref-process-band"><div class="demo-container"><div>${kicker('Easy as one, two, three')}<h2>Less wondering.<br>More getting it sorted.</h2></div><ol>${[['Tell us the job','A repair, an upgrade, or a new idea.'],['Talk through the options','Understand the work and next steps.'],['Make a plan','Agree on what your home needs.']].map(([h,p],i)=>`<li><span>${i+1}</span><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol></div></section>${photoTiles(e)}${closing(e)}`;}

function plumbingHome(e){return `<section class="ref-plumbing-hero">${photo('plumbing-sink-work',{eager:true,cls:'ref-plumbing-background'})}<div class="demo-container"><div class="ref-plumbing-copy">${kicker('Plumbing problems? Start here.')}<h1>Less dripping.<br>Less worrying.<br><span>More living.</span></h1><p>Leaks, drains, and water heaters.<br>Help for the things your home depends on.</p>${action(e)}<a class="ref-secondary" href="#find-help">Help me find the right service ${icon('arrow')}</a></div><div class="ref-plumbing-tag">${icon('water')}A little help.<br><strong>A home that works.</strong></div></div></section><section class="ref-plumbing-help demo-container"><div><span>WHAT’S GOING ON?</span><h2>Find your fix.</h2></div>${tradeServices.clearflow.map(([symbol,name,,route])=>`<a href="${href(e,route)}">${icon(symbol)}${name}${icon('arrow')}</a>`).join('')}</section><section class="demo-section demo-container ref-plumbing-intro"><div>${kicker('Less disruption. Clearer answers.')}<h2>Big plumbing words?<br><span>You don’t need them.</span></h2><p>Tell us where the water is going, what’s making a noise, or why the shower’s gone cold. We’ll start from there.</p><ul class="ref-checks"><li>${icon('check')}Start with the problem you can see</li><li>${icon('check')}Understand the possible next steps</li><li>${icon('check')}Find information for your home</li></ul>${action(e,'See what to expect','what-to-expect','demo-text-link')}</div><div class="ref-plumbing-photo">${photo('drain-inspection')}<span>Everyday plumbing.<br><strong>Everyday peace of mind.</strong></span></div></section>${serviceFinder(e)}<section class="ref-hotwater"><div class="demo-container"><div>${icon('sun')}</div><div>${kicker('Let’s talk hot water')}<h2>Cold shower?<br>Let’s warm things up.</h2><p>Explore repairs, replacements, and the questions worth asking.</p></div>${action(e,'Water heater help','water-heaters')}</div></section>${photoTiles(e)}${closing(e)}`;}

function roofingHome(e){return `<section class="ref-roof-hero">${photo('roof-repair',{eager:true,sizes:'100vw'})}<div class="demo-container"><div class="ref-roof-copy">${kicker('Care for what covers you')}<h1>A stronger roof.<br>A home ready<br>for what’s next.</h1><p>Roof repairs, replacements, and assessments.<br>Start with a clear picture of your roof.</p>${action(e,'Explore roofing services','roofing')}</div>${shortRequest(e)}</div><span class="ref-roof-caption">RIDGELINE ROOFING · RESIDENTIAL ROOF CARE</span></section><div class="ref-roof-promise"><div class="demo-container"><span>${icon('roof')}Your roof, understood</span><span>${icon('check')}Your options, explained</span><span>${icon('home')}Your next step, clear</span></div></div><section class="demo-section demo-container"><div class="ref-section-head"><div>${kicker('Roofing for the way you live')}<h2>From a small repair<br>to a fresh start.</h2></div><p>Find the right place to start.<br>We’ll take it one step at a time.</p></div>${serviceCards(e)}</section><section class="ref-roof-about"><div class="demo-container"><div>${photo('roof-repair')}</div><div>${kicker('Look closer. Choose with confidence.')}<h2>Your home is personal.<br>Your roofing plan<br>should be, too.</h2><p>A good decision starts with the roof in front of you. Understand its condition, compare your options, and plan the work around what it needs.</p>${action(e,'How an assessment works','assessment-process')}</div></div></section><section class="demo-container demo-section ref-roof-guide"><div>${kicker('Repair or replace?')}<h2>You don’t need<br>the answer yet.</h2><p>A leak doesn’t always mean a new roof. Our simple guide helps you understand what’s worth discussing.</p>${action(e,'Find your starting point','repair-or-replace')}</div><div class="ref-roof-options">${[['01','One leak or damaged area','Find the source before choosing the solution.'],['02','Wear across the roof','Look at the condition of the whole roof.'],['03','Not sure what you’re seeing','Start with an assessment and useful questions.']].map(([n,h,p])=>`<a href="${href(e,'repair-or-replace')}"><span>${n}</span><div><h3>${h}</h3><p>${p}</p></div>${icon('arrow')}</a>`).join('')}</div></section>${photoTiles(e)}${closing(e)}`;}

export function referenceHome(e){return ({current:electricHome,clearflow:plumbingHome,ridgeline:roofingHome})[e.theme](e);}

export function referenceShell(e,page,content){
  const primary=tradeServices[e.theme];const contact=target(e);
  const requestHref=page===contact?'#demo-request':href(e,contact)+(Object.keys(requestParameters(e,page)).length?'?'+new URLSearchParams(requestParameters(e,page)):'');
  const logo=`<a class="demo-brand ref-brand" href="${href(e)}">${icon(e.theme==='current'?'bolt':e.theme==='clearflow'?'water':'roof')}<span>${e.theme==='current'?'CURRENT':e.theme==='clearflow'?'CLEARFLOW':'RIDGELINE'}<small>${e.theme==='current'?'ELECTRIC':e.theme==='clearflow'?'PLUMBING':'ROOFING'}</small></span></a>`;
  const nav=`<a href="${href(e,e.theme==='ridgeline'?'roofing':'services')}">Our services</a><a href="${href(e,e.theme==='current'?'our-approach':e.theme==='clearflow'?'what-to-expect':'assessment-process')}">Our approach</a><a href="${href(e,'gallery')}">Gallery</a><a href="${href(e,'questions')}">FAQs</a>${allPagesNavigation(e,page)}`;
  return `<a class="skip-link" href="#demo-main">Skip to website content</a><aside class="demo-banner" aria-label="Example website notice"><div><span class="demo-pill">LIVE PROTOTYPE</span><span>Fictional business · Explore every page</span></div><div><a href="/examples/${e.slug}/">Back to examples</a><a href="/book/?example=${e.slug}">Get a website like this ${icon('arrow')}</a></div></aside><div class="demo-shell theme-${e.theme} reference-trade"><div class="ref-utility"><div class="demo-container"><span>${e.theme==='current'?'A brighter everyday starts at home.':e.theme==='clearflow'?'Plumbing help. Without the guesswork.':'Residential roof repairs & replacement'}</span><a href="${requestHref}">${icon('phone')}Contact now</a></div></div><header class="ref-header"><div class="demo-container demo-header">${logo}<nav class="demo-nav" aria-label="Example website navigation">${nav}</nav><a class="demo-button ref-header-action" href="${requestHref}">Contact now ${icon('arrow')}</a><details class="demo-mobile"><summary>Menu</summary><nav aria-label="Example mobile navigation">${e.routes.map((r,i)=>`<a href="${href(e,r)}" ${page===r?'aria-current="page"':''}>${e.pages[i]}</a>`).join('')}</nav></details></div></header>${e.theme==='clearflow'?`<nav class="ref-plumbing-nav" aria-label="Plumbing services"><div class="demo-container">${primary.map(([,name,,r])=>`<a href="${href(e,r)}">${name}</a>`).join('')}</div></nav>`:''}<div id="demo-main">${content}</div><footer class="demo-footer"><div class="demo-container"><div class="demo-footer-top"><div>${logo}<p>${e.theme==='current'?'Good energy. Great service.':e.theme==='clearflow'?'A little help. A home that works.':'Good homes deserve sound roofs.'}</p>${action(e)}</div><nav aria-label="Example footer navigation">${e.routes.map((r,i)=>`<a href="${href(e,r)}">${e.pages[i]}</a>`).join('')}</nav></div><div class="demo-footer-bottom"><span>Fictional ${e.category.toLowerCase()} prototype by SkipManual. <a href="/website-information/#photo-credits">Photography & credits</a>.</span><a href="/examples/${e.slug}/">About this design ${icon('arrow')}</a></div></div></footer><nav class="example-mobile-action" aria-label="Quick website actions"><a href="${href(e,e.theme==='ridgeline'?'roofing':'services')}">Our services</a><a class="demo-button" href="${requestHref}">Contact now ${icon('arrow')}</a></nav></div>`;
}
