import {photo as responsivePhoto} from '../components/photos.mjs';
import { icon, escape } from '../components/ui.mjs';

const link = (e, label, route = '', service = '', cls = 'demo-button') => {
  const [page,fragment]=route.split('#');
  const path=fragment&&!page?'':`/demos/${e.slug}/${page ? `${page}/` : ''}`;
  return `<a class="${cls}" href="${path}${service ? `?service=${encodeURIComponent(service)}` : ''}${fragment ? `#${fragment}` : ''}">${label}${icon('arrow')}</a>`;
};
const kicker = text => `<p class="demo-kicker">${text}</p>`;
const photo=(name,alt,eager=false)=>responsivePhoto(name,{alt,eager,sizes:name==='roofing'?'100vw':'(max-width:760px) 100vw, 50vw'});
const closing = (e, heading, text) => `<section class="trade-closing"><div class="demo-container"><div><h2>${heading}</h2><p>${text}</p></div>${link(e,e.theme === 'clearflow' ? 'Request a visit' : 'Request an assessment', e.routes[3])}</div></section>`;

const plumbing = [
  { id:'leaks', name:'Leaks & fixtures', icon:'water', problem:'A tap won’t stop dripping.', text:'From a dripping faucet to a leaking connection, start by telling us where you see water and when it happens.', detail:'We look at the fixture and its connections, explain what needs attention, and discuss repair or replacement options.', service:'Leaks & fixtures', route:'leaks-and-fixtures' },
  { id:'drains', name:'Drains & blockages', icon:'flow', problem:'The water is going nowhere.', text:'A slow sink, a backed-up shower, or a toilet that keeps blocking. Tell us which fixtures are affected.', detail:'Understanding whether one fixture or several are affected helps guide the assessment. The cause and access determine the next step.', service:'Drains & blockages', route:'drains' },
  { id:'hot-water', name:'Water heaters', icon:'sun', problem:'The shower has gone cold.', text:'No hot water, inconsistent temperature, or a system you are ready to replace. Let’s work out where to start.', detail:'An assessment considers your system, the symptoms, its condition, and your household’s hot-water needs.', service:'Water heaters', route:'water-heaters' },
  { id:'installations', name:'New fixtures', icon:'home', problem:'Time for something new.', text:'A kitchen update, a bathroom refresh, or a replacement fixture. Bring your plans and we’ll talk through the plumbing.', detail:'Before installation, we review compatibility, available connections, access, and the work involved.', service:'New fixtures', route:'bathroom-kitchen' },
];

function serviceFinder(e) {
  return `<section class="clearflow-finder demo-container" id="find-help" data-choice-group><div>${kicker('Start with what’s happening')}<h2>What needs a<br>little attention?</h2><p>You don’t need the technical words.<br>Choose the situation that sounds familiar.</p><div class="trade-choices" data-choice-controls hidden role="group" aria-label="Choose a plumbing problem">${plumbing.map((s,i)=>`<button type="button" data-choice="${s.id}" aria-controls="help-${s.id}" aria-pressed="${i===0}">${icon(s.icon)}${s.name}${icon('arrow')}</button>`).join('')}</div></div><div>${plumbing.map(s=>`<article class="finder-answer" id="help-${s.id}" data-choice-panel="${s.id}"><span class="finder-symbol">${icon(s.icon)}</span>${kicker(s.name)}<h3>${s.problem}</h3><p>${s.text}</p>${link(e,'Tell us about it','request-a-visit',s.service)}<a class="trade-inline" href="/demos/${e.slug}/${s.route}/">See what this service covers</a></article>`).join('')}</div></section>`;
}

function clearflowHome(e) {
  return `<section class="clearflow-hero demo-container"><div>${kicker('A little help. A home that works.')}<h1>Let’s get your<br>home back<br>to <span>normal.</span></h1><p>Dripping taps. Slow drains. Cold showers.<br>Tell us what’s happening. We’ll help you<br class="desktop-break"> take the next step.</p><div class="trade-actions">${link(e,'Find the help you need','#find-help')}${link(e,'Request a visit','request-a-visit','','demo-text-link')}</div><div class="clearflow-hero-note">${icon('water')}Plumbing for the everyday.<br>And the days that don’t go to plan.</div></div><figure class="clearflow-picture">${photo('plumbing','A bright bathroom with a white bathtub, basin, and chrome fixtures',true)}<figcaption><span>Less disruption.</span><strong>More getting on<br>with your day.</strong>${icon('water')}</figcaption></figure></section><div class="clearflow-ribbon demo-container"><span>01 &nbsp; Tell us the problem</span><span>02 &nbsp; Understand your options</span><span>03 &nbsp; Plan the next step</span></div>${serviceFinder(e)}<section class="clearflow-hotwater"><div class="demo-container"><span class="water-illustration" aria-hidden="true">${icon('sun')}</span><div>${kicker('Let’s talk hot water')}<h2>A good day starts<br>with a warm shower.</h2><p>Repair the system you have, or explore a replacement? Start with the symptoms, your household, and the questions worth asking.</p>${link(e,'Understand your water heater','water-heaters','','demo-text-link')}</div></div></section>${closing(e,'Something not quite right?','Start with what you know. We’ll take it from there.')}`;
}

function clearflowServices(e) {
  return `<section class="demo-page-hero demo-container">${kicker('Residential plumbing')}<h1>Small drip.<br><span>Big inconvenience.</span></h1><p>Useful help for the plumbing you rely on every day.<br>Find your problem below, then tell us a little more.</p></section><section class="demo-container plumbing-service-grid">${plumbing.map(s=>`<article id="${s.id}"><span class="plumbing-service-icon">${icon(s.icon)}</span><h2>${s.name}</h2><h3>${s.problem}</h3><p>${s.detail}</p>${link(e,'Explore this service',s.route,'','demo-text-link')}</article>`).join('')}</section><aside class="trade-note demo-container"><strong>Active leak?</strong><p>If it is safe and you know how, turn off the water supply to limit damage. For an urgent situation, contact a real local plumber. This example website does not dispatch help.</p></aside>${closing(e,'Not sure what to call it?','A plain-language description is a good place to start.')}`;
}

function clearflowWater(e) {
  return `<section class="demo-page-hero demo-container">${kicker('Water-heater help')}<h1>Make room for<br><span>reliable hot water.</span></h1><p>When the shower goes cold, the answer starts with a closer look.<br>Here is what to consider before choosing your next step.</p></section><section class="demo-container water-options"><article>${kicker('01 / The system you have')}<h2>Start with<br>the symptoms.</h2><ul><li>Is there no hot water, or just less than usual?</li><li>Does the temperature keep changing?</li><li>Have you noticed a leak or unusual sound?</li><li>How old is the system, if you know?</li></ul><p>An assessment can help establish whether a specific fault can be repaired and whether that makes sense for the system’s condition.</p></article><article>${kicker('02 / A system for your household')}<h2>Think about<br>what you need.</h2><ul><li>How many people use hot water at once?</li><li>What energy supply and space are available?</li><li>Would a tank or tankless system suit the home?</li><li>What installation changes may be needed?</li></ul><p>Equipment, installation, and running costs all matter. Your options depend on your home and should be checked in person.</p></article></section><section class="demo-container demo-section trade-faq"><h2>A few common questions.</h2><details><summary>Does a cold shower mean I need a new heater?</summary><p>Not necessarily. A control, power supply, component, or demand issue could be involved. An assessment should identify the cause before recommending replacement.</p></details><details><summary>Can I choose a larger system?</summary><p>Capacity should match your household, available space, connections, and energy supply. Discuss those together before choosing equipment.</p></details><details><summary>What should I include in my request?</summary><p>Describe the symptoms and include the system type and approximate age if known. You do not need to diagnose the fault yourself.</p></details></section>${closing(e,'Tell us what’s changed.','No hot water, a new household routine, or an aging system. Start there.')}`;
}

const roofServices = [
  ['01','Roof repairs','A specific problem deserves a closer look.','Leaks, damaged roofing, and trouble around flashing or roof penetrations. The first step is identifying where the problem starts.','Roof repairs'],
  ['02','Roof replacement','Plan for the roof’s next chapter.','When wear is widespread, consider the whole system: the covering, underlying condition, ventilation, details, and installation plan.','Roof replacement'],
  ['03','Roof assessments','Understand what you’re looking at.','Start with your concerns and the roof’s visible condition. An assessment helps frame the options and what further investigation may be needed.','Roof assessment'],
];
const roofGuidance = [
  {id:'isolated',label:'One leak or damaged area',title:'Start by finding the source.',text:'An isolated issue may be suitable for a repair when the surrounding roof is in sound condition. The visible leak does not always sit directly below the cause.',questions:['Where and when did you first notice the problem?','Is the surrounding roof in good condition?','What would the repair address, and what would it leave?'],service:'Roof repairs'},
  {id:'widespread',label:'Wear across the roof',title:'Look at the roof as a whole.',text:'Widespread deterioration or repeated issues make a broader assessment useful. Compare the condition of the covering and underlying layers before deciding.',questions:['How extensive is the deterioration?','Have previous repairs addressed the underlying issue?','What is included in a replacement proposal?'],service:'Roof replacement'},
  {id:'unsure',label:'I’m not sure yet',title:'A clearer picture comes first.',text:'You do not need to choose repair or replacement before asking for help. Start with what you have noticed, what you know about the roof, and your plans for the home.',questions:['What is known about the roof’s age and history?','Are there interior signs of moisture?','What can an assessment establish?'],service:'Roof assessment'},
];

function ridgelineHome(e) {
  return `<section class="ridgeline-hero"><div class="demo-container ridge-title"><div>${kicker('A considered approach to roofing')}<h1>Good homes.<br><em>Sound roofs.</em></h1></div><div><p>Repair what needs attention.<br>Replace with a clear plan.<br>Start by understanding your roof.</p>${link(e,'Let’s take a closer look','request-an-assessment')}</div></div><figure class="ridge-landscape">${photo('roofing','A house framed by trees with a pitched roof and a broad front porch',true)}<figcaption><span>THE VIEW STARTS AT HOME.</span><span>RIDGELINE / RESIDENTIAL ROOFING</span></figcaption></figure></section><section class="demo-container ridge-intro demo-section"><div>${kicker('Care for what covers you')}<h2>Every roof has<br>its own <em>story.</em></h2></div><div><p>A small leak. Years of wear. A home ready for its next chapter. The right approach starts with the condition of your roof and the way you want to move forward.</p>${link(e,'Explore our approach','roofing','','demo-text-link')}</div></section><section class="ridge-service-band"><div class="demo-container">${roofServices.map(([n,name,heading,text,service])=>`<article><span>${n} /</span><h2>${name}</h2><p>${heading}</p>${link(e,'Explore this service','roofing', '', 'demo-text-link').replace('/roofing/"',`/roofing/#service-${n}"`)}</article>`).join('')}</div></section><section class="demo-container ridge-decision demo-section"><div class="ridge-line-art" aria-hidden="true"><svg viewBox="0 0 420 300" fill="none"><path d="M25 180 170 50l145 130M90 190 235 60l160 140M60 160v110h220V150M125 168v102M280 270l80-65v-42M170 50l65 10M280 270H60" stroke="currentColor" stroke-width="1.5"/><path d="M160 270v-80h60v80M35 287h345" stroke="currentColor" stroke-width="1.5"/></svg><span>UNDERSTAND. THEN DECIDE.</span></div><div>${kicker('The question homeowners ask')}<h2>Repair.<br>Replace.<br><em>Let’s find the why.</em></h2><p>A useful decision starts with better questions. Explore the factors that help shape the conversation.</p>${link(e,'Explore the roof guide','repair-or-replace','','demo-text-link')}</div></section>${closing(e,'A roof worth<br>thinking through.','Tell us what you have noticed. We’ll start there.')}`;
}

function ridgelineServices(e) {
  return `<section class="demo-page-hero demo-container">${kicker('The work, considered')}<h1>From a small repair<br>to a <em>fresh start.</em></h1><p>Your roof’s condition comes first. Explore the possibilities<br>and the details that belong in the conversation.</p></section><section class="demo-container ridge-services">${roofServices.map(([n,name,heading,text,service])=>`<article id="service-${n}"><span>${n} /</span><div><h2>${name}</h2><h3>${heading}</h3></div><div><p>${text}</p>${link(e,'Explore this service',n==='01'?'roof-repairs':n==='02'?'roof-replacement':'assessment-process','','demo-text-link')}</div></article>`).join('')}</section><section class="demo-container demo-section roof-materials">${kicker('A look at materials')}<h2>The finish is only<br>part of the <em>picture.</em></h2><p>Suitability depends on the roof structure, pitch, local conditions, and installation requirements.</p><div>${[['Shingles','A familiar, layered finish.','Discuss product grades, ventilation, expected upkeep, and the details around edges and openings.'],['Metal','Clean lines. Many profiles.','Consider the specific system, expansion, fasteners, finish, and compatibility with the roof’s shape.'],['Tile','Texture and lasting character.','Check structural load, pitch, underlayment, and the care needed when individual tiles are damaged.']].map(([name,heading,text],i)=>`<article><div class="material-swatch material-${i}" aria-hidden="true"></div><h3>${name}</h3><strong>${heading}</strong><p>${text}</p></article>`).join('')}</div></section>${closing(e,'First, a closer look.','Choose your next step with the roof in view.')}`;
}

function ridgelineGuide(e) {
  return `<section class="demo-page-hero demo-container">${kicker('A homeowner’s field guide')}<h1>Repair or replace?<br><em>Start with the roof.</em></h1><p>Age is one part of the picture. Condition, the extent of the problem,<br>and the details of the roof matter too.</p></section><section class="demo-container roof-guide" data-choice-group><div><h2>What brought<br>you here?</h2><p>Choose the situation closest to yours.</p><div class="trade-choices" data-choice-controls hidden role="group" aria-label="Choose your roof situation">${roofGuidance.map((g,i)=>`<button type="button" data-choice="${g.id}" aria-controls="roof-${g.id}" aria-pressed="${i===0}"><span>0${i+1} /</span>${g.label}${icon('arrow')}</button>`).join('')}</div></div><div>${roofGuidance.map(g=>`<article class="roof-guide-answer" id="roof-${g.id}" data-choice-panel="${g.id}">${kicker('Questions before conclusions')}<h3>${g.title}</h3><p>${g.text}</p><h4>Worth asking</h4><ul>${g.questions.map(q=>`<li>${q}</li>`).join('')}</ul>${link(e,'Talk through this situation','request-an-assessment',g.service)}</article>`).join('')}</div></section><aside class="trade-note demo-container"><strong>A guide to the conversation.</strong><p>This guide cannot diagnose a roof or replace an in-person assessment. Observe from the ground; do not climb onto the roof to use this guide. This is a fictional example website.</p></aside>${closing(e,'You don’t need<br>the answer yet.','A description of the problem is a useful place to start.')}`;
}

function tradeContact(e) {
  const isPlumbing=e.theme==='clearflow';
  const services=isPlumbing?plumbing.map(s=>s.service):roofServices.map(s=>s[4]);
  return `<section class="demo-page-hero demo-container">${kicker(isPlumbing?'A little help starts here':'Your roof, in focus')}<h1>${isPlumbing?'Tell us what<br><span>needs attention.</span>':'Let’s start with<br><em>a closer look.</em>'}</h1></section><section class="demo-container demo-contact"><div><h2>${isPlumbing?'Your words.<br>A useful starting point.':'A little context.<br>A better conversation.'}</h2><p>${isPlumbing?'Describe the drip, the drain, or the cold shower. You don’t need to know what has caused it.':'Tell us what you have noticed and what you know about the roof. You can ask for an assessment without choosing repair or replacement.'}</p><aside class="demo-disclosure"><strong>This is an example website.</strong><p>${isPlumbing?'No plumbing visit':'No roofing assessment'} will be arranged. This is a fictional business. Use sample details; the form does not send or store information.</p></aside></div><form id="demo-request" class="demo-request-form" tabindex="-1" data-demo-form data-demo-type="${e.theme}"><p class="form-intro">Try the ${isPlumbing?'visit':'assessment'} request. * Required.</p><div class="form-grid"><div class="field full"><label for="demo-name">Sample name *</label><input id="demo-name" name="name" required maxlength="100" placeholder="Alex Example"></div><div class="field full"><label for="demo-service">What can we help with? *</label><select id="demo-service" name="service" required><option value="">Choose a service</option>${[...services,'Help me choose'].map(s=>`<option>${escape(s)}</option>`).join('')}</select></div><div class="field full"><label for="demo-project">${isPlumbing?'What is happening?':'What have you noticed?'} *</label><textarea id="demo-project" name="project" required maxlength="2000" placeholder="${isPlumbing?'For example: the kitchen tap keeps dripping.':'For example: a damp patch near the upstairs window after rain.'}"></textarea></div></div><button class="demo-button" type="submit" data-js-submit disabled>Preview request${icon('arrow')}</button><p class="form-feedback" role="status" aria-live="polite" tabindex="-1"></p><noscript><p>Enable JavaScript to preview the request. Nothing will be sent.</p></noscript></form></section>`;
}

export const tradeRoutes = {
  clearflow: [['','Home',clearflowHome],['services','Plumbing services',clearflowServices],['water-heaters','Water heaters',clearflowWater],['request-a-visit','Request a visit',tradeContact]],
  ridgeline: [['','Home',ridgelineHome],['roofing','Roofing services',ridgelineServices],['repair-or-replace','Repair or replace?',ridgelineGuide],['request-an-assessment','Request an assessment',tradeContact]],
};
