import { packageServices, scenarios } from '../data/package.mjs';
import { icon, eyebrow, textLink, escape } from './ui.mjs';

export function packageOverview() {
  return `<section class="section container package-overview"><div class="section-head"><div>${eyebrow('One package. Fewer loose ends.')}<h2>A good website.<br>And the follow-through.</h2></div><p>Give customers somewhere to find you, a way to reach you, and a reply when you’re busy. All five services are part of the $249/month package.</p></div><div class="package-grid">${packageServices.map((s,i)=>`<a href="/services/#${s.id}" class="package-item"><span class="package-icon">${icon(s.icon)}<small>0${i+1}</small></span><h3>${s.short}</h3><p>${['A clear place to show what you do.','Keep a new conversation moving.','Give a missed caller a way to reply.','Make asking for feedback routine.','Help search engines understand your site.'][i]}</p><span class="package-more">See how it works ${icon('arrow')}</span></a>`).join('')}</div></section>`;
}

export function scenarioSection() {
  return `<section class="section scenario-section"><div class="container" data-choice-group><div class="section-head"><div>${eyebrow('Here’s what that looks like')}<h2>Real life gets busy.<br>Keep the conversation going.</h2></div><p>No marketing dictionary needed.<br>Choose an everyday moment to see how the follow-up can work.</p></div><div class="scenario-choices" data-choice-controls hidden role="group" aria-label="Choose an everyday business example">${scenarios.map((s,i)=>`<button type="button" data-choice="${s.id}" aria-pressed="${i===0}" aria-controls="scenario-${s.id}"><span>0${i+1}</span>${s.label}${icon('arrow')}</button>`).join('')}</div>${scenarios.map(s=>`<article id="scenario-${s.id}" class="scenario-panel" data-choice-panel="${s.id}"><div class="scenario-copy">${eyebrow(s.business)}<h3>${s.heading}</h3><p>${s.text}</p><div class="scenario-outcome">${icon('check')}<p>${s.outcome}</p></div>${textLink('What’s in the package','/services/')}</div><div class="conversation"><div class="conversation-header"><span class="conversation-avatar">${icon('phone')}</span><div><strong>${s.business}</strong><span>Illustrative conversation</span></div><span class="conversation-label">EXAMPLE</span></div><p class="conversation-trigger">${s.trigger}</p><div class="conversation-messages">${s.messages.map(m=>`<div class="message message--${m.kind}"><span>${m.kind==='customer'?'Customer':m.kind==='system'?'Reminder':'Automatic reply'}</span><p>${escape(m.text)}</p></div>`).join('')}</div><p class="conversation-note">${s.note}</p></div></article>`).join('')}</div></section>`;
}
