import { button, eyebrow, faqList, icon, preview, textLink, escape } from './ui.mjs';
import { examples } from '../data/examples.mjs';
import { faqs, testimonials } from '../data/site.mjs';

const loopSteps = [
  { label: 'First impression', title: 'A look that feels like you.', copy: 'Thoughtful design gives your business a place to belong.', page: 'Home', heading: 'A little more you.<br>A lot more possibility.', caption: 'A fresh perspective. A thoughtful approach.', action: 'Discover what we do', art: '01' },
  { label: 'Room to explore', title: 'More than a pretty homepage.', copy: 'Clear pages help people understand what you have to offer.', page: 'Our approach', heading: 'Good things start<br>with understanding.', caption: 'Your story, your services, your way of working.', action: 'Explore our approach', art: '02' },
  { label: 'Easy next steps', title: 'A conversation starts here.', copy: 'Simple contact paths turn interest into a useful next step.', page: 'Get in touch', heading: 'Something in mind?<br>Let’s talk about it.', caption: 'A question, an idea, a new beginning.', action: 'Start a conversation', art: '03' },
];

function websiteLoop() {
  return `<div class="studio-loop" data-studio-loop data-active="0" role="group" aria-label="An illustrative website journey">
    <div class="studio-loop-topline"><span><i aria-hidden="true"></i> A website, coming together</span><span>DESIGN IN MOTION</span></div>
    <div class="studio-canvas">
      <div class="studio-orbit" aria-hidden="true"></div><span class="studio-canvas-note" aria-hidden="true">Made to feel like you.</span>
      <div class="studio-browser"><div class="studio-browser-chrome" aria-hidden="true"><span>● ● ●</span><span>YOUR ONLINE SPACE</span>${icon('diagonal')}</div>
        <div class="studio-browser-nav" aria-hidden="true"><strong>your brand<span>®</span></strong><span>Thoughtfully yours.</span></div>
        <div class="studio-frames">${loopSteps.map((s,i)=>`<div class="studio-frame studio-frame--${i}" data-studio-frame ${i?'aria-hidden="true" inert':''}>
          <div class="studio-demo-copy"><span class="studio-demo-kicker">${s.page}</span><p class="studio-demo-heading">${s.heading}</p><p class="studio-demo-description">${s.caption}</p><span class="studio-demo-action">${s.action}${icon('arrow')}</span></div>
          <div class="studio-art studio-art--${i}" aria-hidden="true"><div class="studio-art-disc"></div><div class="studio-art-arch"></div><div class="studio-art-line"></div><span>${s.art} / A NEW PERSPECTIVE</span></div>
        </div>`).join('')}</div>
        <div class="studio-browser-footer" aria-hidden="true"><span>Designed around your business.</span><span>Purpose in every detail. ↗</span></div>
      </div>
      <div class="studio-mobile" aria-hidden="true"><span class="studio-mobile-camera"></span><strong>your brand</strong><div class="studio-mobile-art"><span></span></div><span class="studio-mobile-title">Beautiful.<br>At every size.</span><div class="studio-mobile-lines"><i></i><i></i></div><span class="studio-mobile-button">Let’s connect ↗</span></div>
      <span class="studio-design-stamp" aria-hidden="true">A little<br><em>more you.</em> ✳</span>
    </div>
    <div class="studio-loop-caption">${loopSteps.map((s,i)=>`<div data-studio-caption ${i?'hidden':''}><strong>${s.title}</strong><p>${s.copy}</p></div>`).join('')}<button type="button" class="studio-motion-control" data-studio-pause aria-label="Pause website animation" hidden><span data-studio-pause-icon aria-hidden="true">Ⅱ</span><span data-studio-pause-label>Pause</span></button></div>
    <div class="studio-loop-steps" role="group" aria-label="Website journey" data-studio-controls hidden>${loopSteps.map((s,i)=>`<button type="button" data-studio-step="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${s.label}<i aria-hidden="true"></i></button>`).join('')}</div>
    <noscript><p class="studio-static-note">Thoughtful design. Clear pages. Simple ways to get in touch.</p></noscript>
  </div>`;
}

function studioWork() {
  const selected = ['form-studio', 'olive-and-ember', 'current-electric'].map(slug=>examples.find(e=>e.slug===slug));
  const directions = ['Soft & expressive', 'Warm & editorial', 'Bold & confident'];
  return `<section class="studio-section studio-work" id="website-examples"><div class="container"><div class="studio-section-heading"><div>${eyebrow('Different brands. Different possibilities.')}<h2>One studio.<br><em>More than one style.</em></h2></div><div><p>Your business has its own personality.<br>Your website should have one, too.</p>${textLink('Explore all website examples','/examples/')}</div></div><div class="portfolio-grid">${selected.map((e,i)=>`<article class="portfolio-card portfolio-card--${e.theme}"><a class="portfolio-image" href="/demos/${e.slug}/" aria-label="Explore the ${escape(e.name)} example website">${preview(e)}<span class="portfolio-open">Explore the website ${icon('diagonal')}</span></a><div class="portfolio-meta"><div><p>${directions[i]} <span>· Design concept</span></p><h3><a href="/demos/${e.slug}/">${escape(e.name)}</a></h3></div><a href="/examples/${e.slug}/" class="portfolio-details" aria-label="About the ${escape(e.name)} design">${icon('arrow')}</a></div></article>`).join('')}</div><p class="studio-work-note">Original concepts for fictional businesses. Each opens into a complete, ten-page example website.</p></div></section>`;
}

function studioReviews() {
  return `<section class="studio-section studio-reviews" id="client-feedback"><div class="container"><div class="studio-section-heading"><div>${eyebrow('A few words from our clients')}<h2>Good work starts<br><em>with good relationships.</em></h2></div><p>Five-star feedback about working together<br>and building a better presence online.</p></div><div class="studio-review-grid">${testimonials.map(t=>`<article class="studio-review"><div class="studio-stars" role="img" aria-label="${t.rating} out of 5 stars"><span aria-hidden="true">★★★★★</span></div><p>${escape(t.summary)}</p><div class="studio-review-person"><span class="studio-avatar" aria-hidden="true">${t.initials}</span><span><strong>${escape(t.name)}</strong><small>Client feedback</small></span></div></article>`).join('')}</div><p class="studio-review-note">Paraphrased from client feedback shared with us; these are summaries, not verbatim quotes.</p></div></section>`;
}

export function studioHome() {
  return `<section class="studio-hero"><div class="container studio-hero-grid"><div class="studio-hero-copy">${eyebrow('Independent web design studio')}<h1>Your business.<br><em>Beautifully</em><br>online.</h1><p>Websites with personality, purpose, and a clear next step. Designed around your business, wherever you’re headed.</p><div class="actions">${button('Let’s build your website','/book/')}${textLink('Explore our work','#website-examples')}</div><div class="studio-hero-proof"><span class="studio-proof-stars" aria-hidden="true">★★★★★</span><a href="#client-feedback">Five clients. Five-star feedback.${icon('arrow')}</a></div></div>${websiteLoop()}</div><div class="container studio-hero-bottom"><span>A fresh start. A thoughtful redesign. Your next chapter.</span><a href="#studio-services">There’s more to a good website ${icon('arrow')}</a></div></section>
  <nav class="studio-section-index container" aria-label="Explore this page"><a href="#studio-services">01 <span>What we do</span></a><a href="#website-examples">02 <span>Design examples</span></a><a href="#studio-process">03 <span>The process</span></a><a href="#client-feedback">04 <span>Client feedback</span></a></nav>
  <section class="studio-section container" id="studio-services"><div class="studio-section-heading"><div>${eyebrow('Thoughtful from the first click')}<h2>Looks like you.<br><em>Works for your business.</em></h2></div><p>A strong online presence brings design, content, and the customer journey together. We help you connect the pieces.</p></div><div class="studio-service-grid"><article><span class="studio-service-number">01 / DESIGN</span>${icon('layout')}<h3>A website with character.</h3><p>A new website or a fresh take on your current one, with a visual direction that feels right for your business.</p>${textLink('Website design','/services/business-websites/')}</article><article><span class="studio-service-number">02 / EXPERIENCE</span>${icon('cursor')}<h3>Clarity on every page.</h3><p>Useful content, intuitive navigation, and a layout that feels just as considered on a phone as on a desktop.</p>${textLink('Explore our approach','/how-it-works/')}</article><article><span class="studio-service-number">03 / CONNECTION</span>${icon('flow')}<h3>Keep the conversation going.</h3><p>Clear contact paths, helpful follow-up, and search foundations that support your presence online.</p>${textLink('See all services','/services/')}</article></div></section>
  ${studioWork()}
  <section class="studio-section container studio-depth"><div class="studio-page-stack" aria-hidden="true"><div class="studio-page-sheet studio-sheet-back"><span>03 · LET’S CONNECT</span><b>The next step,<br>made simple.</b><i></i><i></i><i></i></div><div class="studio-page-sheet studio-sheet-middle"><span>02 · WHAT YOU DO</span><b>Give your work<br>room to speak.</b><div class="studio-sheet-tiles"><i></i><i></i></div></div><div class="studio-page-sheet studio-sheet-front"><span>01 · YOUR STORY</span><b>Every business<br>has a story.</b><div class="studio-sheet-art"></div><i></i><i></i></div></div><div>${eyebrow('A whole website. A complete picture.')}<h2>Give your story<br><em>a little more space.</em></h2><p>Your homepage opens the door. Dedicated pages give people room to understand your services, get to know you, and feel ready to reach out.</p><ul class="studio-check-list"><li>${icon('check')}10–20 pages planned around your business</li><li>${icon('check')}Thoughtful layouts for phones and desktops</li><li>${icon('check')}Page titles, descriptions, and search foundations</li></ul>${textLink('What goes into your website','/services/business-websites/')}</div></section>
  <section class="studio-section studio-process" id="studio-process"><div class="container"><div class="studio-section-heading"><div>${eyebrow('A clear process. A real conversation.')}<h2>You bring the business.<br><em>We bring it to life online.</em></h2></div>${textLink('Get to know the process','/how-it-works/')}</div><ol class="studio-process-grid"><li><span>01</span><h3>Let’s get to know you.</h3><p>Your business, your ideas, and what you’d like your website to do.</p></li><li><span>02</span><h3>Give it a direction.</h3><p>We agree on the pages, content, visual style, and project scope.</p></li><li><span>03</span><h3>See it take shape.</h3><p>Explore your website on desktop and mobile. Share your feedback.</p></li><li><span>04</span><h3>Make it ready.</h3><p>We check the details together and agree on the launch and handover.</p></li></ol></div></section>
  ${studioReviews()}
  <section class="studio-section container studio-about"><span class="studio-about-symbol" aria-hidden="true">✳</span><div>${eyebrow('Hello. We’re SkipManual.')}<h2>Care for the details.<br><em>Room for your ideas.</em></h2></div><div><p>We believe a business website should feel personal and be easy to use. So we start by listening, explain things clearly, and give every page a reason to be there.</p>${textLink('A little about us','/about/')}</div></section>
  <section class="studio-section container friendly-faq"><div class="faq-layout"><div>${eyebrow('Before we begin')}<h2>A few questions.<br><em>A little clarity.</em></h2>${textLink('More questions, answered','/faq/')}</div>${faqList([faqs[2],faqs[6],{q:'Can you design for my kind of business?',a:'Tell us what you do and what you have in mind. We design around your business, audience, and goals. Our example websites show different design directions, and we’ll discuss the right fit with you.'},faqs[5]])}</div></section>
  <section class="studio-final"><div class="container">${eyebrow('Let’s make something that feels like you.')}<h2>Your next chapter.<br><em>Let’s design it.</em></h2><p>Bring an idea, a website that needs a rethink, or just a few questions.</p><div class="actions">${button('Tell us what you have in mind','/book/')}${textLink('Browse the website examples','/examples/')}</div><a class="studio-pricing-link" href="/pricing/">Explore pricing & package details ${icon('arrow')}</a></div></section>`;
}
